name: Initial Scope

on:
  workflow_dispatch:
    inputs:
      scope:
        description: "Enter Scope name"
        required: true
      alias:
        description: "Enter Scope alias"
        required: true

jobs:
  init-scope:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --depth=1 git@github.com:wliamp/java.git ${{ runner.temp }}/java

      - run: |
          bash $GITHUB_WORKSPACE/.shell/init-scope
        env:
          SCOPE: ${{ github.event.inputs.scope }}
          ALIAS: ${{ github.event.inputs.alias }}
          TEMP: ${{ runner.temp }}/java

      - uses: ./.github/actions/init-scope
        with:
          scope: ${{ github.event.inputs.scope }}
          in_key: ${{ secrets.CONTRACT_DK }}
          ex_key: ${{ secrets.JAVA_DK }}
