description: "Checks if a repo variable for a given scope exists, and creates it if it doesn't."
inputs:
  scope:
    description: "business domain scope"
    required: true
  pat:
    description: "Template repository PAT"
    required: true
runs:
  using: node20
  main: dist/index.js
