description: |
  Manage a simple key=value map file.
  This action performs the following steps:
  - Reads a text file (map) containing lines in the format `key=value`.
  - Loads all existing entries into memory as an object.
  - Checks if the given key or value already exists:
    - If found, returns the existing pair immediately without modifying the file.
    - If not found, appends the new `key=value` pair.
  - Sorts all entries by key alphabetically.
  - Writes the updated lines back to the map file.
  - Outputs both `key` and `value` for downstream steps.
inputs:
  key:
    description: "the key to lookup in the map file"
    required: true
  value:
    description: "the value associated with the key"
    required: false
    default: ""
  map:
    description: "path to the map file that stores key=value pairs"
    required: true
runs:
  using: node20
  main: dist/index.js
