description: |
  Adjust project directories and files based on scope–alias mappings.
  This action:
  - Reads `scope`, `service`, and `alias` inputs.
  - Looks up the corresponding scope alias from the `scopes` file.
  - Moves source directories to match the resolved scope and alias structure.
  - Replaces placeholder tags (`<module>`, `<alias1>`, `<alias2>`) in source and config files.
  - Updates `.java`, `.gradle`, `.yml`, and `.toml` files accordingly.
inputs:
  scope:
    description: "business domain scope"
    required: true
  service:
    description: "the service belong to 'scope'"
    required: true
  pat:
    description: "Template repository PAT"
    required: true
  tld:
    description: "top-level domain"
    required: true
  org:
    description: "organization name"
    required: true
runs:
  using: node20
  main: dist/index.js
